version: "3.9"
services:
  db: 
    image: postgres:17
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
     - ./db-init/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
     - "5432:5432"

  server:
    build: ./server
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      TOKEN: ${TOKEN}
    ports:
     - "3000:3000"
    depends_on:
     - db

  test-predyspozycji:
    build: ./test-predyspozycji
    environment:
      TOKEN: SECRET_PHRASE
    ports:
     - "4200:80"
    depends_on:
     - server

volumes:
  db_data:

